### ISSUE TITLE
Safari on mobile phone hides the footer

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#15]
How to reproduce:
- Open website on Safari on iOS (tested on iPhone 12 mini)

The issue:
<img src="https://github.com/miljkovicjovan/minimalist-task-tracker/assets/77690201/8cbbd26a-128d-4e9a-818e-d3e9fb8f7f3f" width="25%"/>

What is expected:
- The footer should be displayed instead of what we have now where it is hidden behind the search.
- Example on the same phone in Brave browser:
<img src="https://github.com/miljkovicjovan/minimalist-task-tracker/assets/77690201/c22ea453-2a84-4d99-8e63-68ada79f5015" width="25%"/>

**Comment by HTQun** [comment]
Hello, I'm very interested in your problem. Can you assigned it to me?

**Comment by miljkovicjovan** [comment]
@HTQun Hello, just checking in to see how is it going with the task are you still interested in doing it ?

**Comment by miljkovicjovan** [comment]
@HTQun Please respond if you want to work on this and I'll assign it back to you but for now this issue is open for anyone.
