### ISSUE TITLE
Editing Readme 

### ISSUE THREAD

**Issue by sshah135** [miljkovicjovan/minimalist-task-tracker#16]
Adding more details in Readme to get better knowledge of the project.

**Comment by miljkovicjovan** [comment]
@sshah135 This is something that should be done I agree. Do you have any idea what should we put there?

**Comment by sshah135** [comment]
@miljkovicjovan sure, you can add more details on how this works, key points of this project so that any user gets some knowledge that what does it provide.
And also you can update the git clone link.

**Comment by txlan1710** [comment]
@miljkovicjovan  @sshah135 I'm capable of providing more detailed information. Could you assign this issue to me, please?

**Comment by miljkovicjovan** [comment]
#17
