### ISSUE TITLE
Create notification bars with text for actions

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#21]
Actions like adding, deleting, editing tasks should be shown to the user 
Example: "Successfully deleted task"

**Comment by erickNjuki** [comment]
something like an alert at the bottom right  corner with the message "Tasks deleted successfully!"

**Comment by miljkovicjovan** [comment]
@erickNjuki yes, it should be a component so we can reuse it for all actions we want

**Comment by erickNjuki** [comment]
If you have not worked on it yet, you can assign it to me

**Comment by miljkovicjovan** [comment]
@erickNjuki are you still up for doing this or not?

**Comment by erickNjuki** [comment]
Not

**Comment by ghost** [comment]
I have created a PR for this, kindly check it. I'm new to this, if there's something that I have done wrong, please let me know, I'll do my best to rectify it
