### ISSUE TITLE
Confirmation modal when editing a task

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#22]

**Comment by tkthib2015012** [comment]
Hello @miljkovicjovan , can I try it?, I think I can do this function.

**Comment by miljkovicjovan** [comment]
Sure you have examples of how I implemented the delete confirmation modals here : #23 #20

**Comment by miljkovicjovan** [comment]
@all-contributors please add @tkthib2015012 for code
