### ISSUE TITLE
Add dateTime field to finished task

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#29]
The dateTime field should be added to a task once it is marked as finished.
The name of the field should be "createdAt" (meaning: created at {date} {time}).

**Comment by LittleCuong** [comment]
Can I have a try?

**Comment by miljkovicjovan** [comment]
Sure @LittleCuong 😁

**Comment by LittleCuong** [comment]
> Sure @LittleCuong 😁

Do you want the createdAt field display at the "Finished Tasks" section or you just want it to be saved at localStorage?

**Comment by miljkovicjovan** [comment]
> Do you want the createdAt field display at the "Finished Tasks" section or you just want it to be saved at localStorage?
> 
> 

This issue is only for creating the field in localStorage

**Comment by LittleCuong** [comment]
I've done it bro. Is there any requirement for push request?
