### ISSUE TITLE
Keep footer to the bottom of the page 

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#34]
I want the footer to be on the bottom of the screen when there is nothing on the page.
The footer should not be sticky but be pushed down by other content if there is any.

**Comment by minhkha912** [comment]
can you explain the issue in detail? I wanna help!

**Comment by draunger** [comment]
Assign me

**Comment by miljkovicjovan** [comment]
> can you explain the issue in detail? I wanna help!

Yes I want the footer to be at the bottom of the page always. 
Right now the footer is displayed like this:
<img width="900" alt="Screenshot 2023-11-02 at 15 25 48" src="https://github.com/miljkovicjovan/minimalist-task-tracker/assets/77690201/197cc4c4-c963-4985-8c78-570dacc781eb">

However I want it to be always displayed like this:
<img width="900" alt="Screenshot 2023-11-02 at 15 26 51" src="https://github.com/miljkovicjovan/minimalist-task-tracker/assets/77690201/f73acb36-4b07-4bda-b06b-fe2572a2fb8b">

So no matter if there are any tasks or not the footer should be at the bottom.


@draunger @minhkha912 you can both work on it and whoever solves the task first and makes a PR I will assign it to them thank you.

**Comment by miljkovicjovan** [comment]
@draunger How is it going ?

**Comment by draunger** [comment]
Facing some difficulty while solving it but will do tomorrow sure..

**Comment by bidzy1617** [comment]
https://github.com/miljkovicjovan/minimalist-task-tracker/pulls PR raised
