### ISSUE TITLE
Big space between active and finished tasks

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#37]
<img width="900" alt="screenshot" src="https://github.com/miljkovicjovan/minimalist-task-tracker/assets/77690201/ef38ccb9-dc66-4a1c-b9e3-41fdd7d61ce0">

**Comment by mallick03** [comment]
Hello, I would like to work on this issue.

**Comment by draunger** [comment]
Assign me

**Comment by miljkovicjovan** [comment]
@mal092, @draunger please tell me if you can reproduce this issue because I can't on my end
