### ISSUE TITLE
When in edit mode disable buttons for that task

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#40]
When in edit mode disable the buttons for finishing, editing and deleting the task that is currently being edited.

**Comment by LittleCuong** [comment]
Can I take this?

**Comment by miljkovicjovan** [comment]
@LittleCuong I have assigned this task to you now please create a separate branch from the latest develop branch on your fork so you are in sync.

**Comment by miljkovicjovan** [comment]
#49
