### ISSUE TITLE
Add a date and time display 

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#5]

**Comment by Sky-De** [comment]
@miljkovicjovan may I ask for some clarification?
Would you like to add time and date to which element or component? where? With what kind of date or time format? How about the style of that? any design?

please clarify then assign this to me
thanks

**Comment by miljkovicjovan** [comment]
@Sky-De This issue is still open for thought. I thought about adding a small time and date display somewhere on the page but I'm still not sure. We can start a discussion around it in the discussion tab. But for now I'll mark it as closed.
