### ISSUE TITLE
Light - Dark Mode

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#56]

**Comment by zablon-oigo** [comment]
Hello, Please Explain more on how you would like this effect i.e. should it be a toggle button or code that detects a user theme automatically?

**Comment by miljkovicjovan** [comment]
@zablon-oigo for this issue simply create a setting in settings modal with a toggle which will change a localstorage value to true or false (dark, light). The default option should be light. And then based on that you need to create logic for the styling to change.

**Comment by zablon-oigo** [comment]
Please assign me, I can tackle this

**Comment by zablon-oigo** [comment]
Hello, I tried running the application locally and I faced an annoying bug, I was wondering if anyone else faced the same issue and how they solved it 
![react bug](https://github.com/miljkovicjovan/minimalist-task-tracker/assets/143833326/d072bb60-add6-4449-a579-9f8511474747)

**Comment by miljkovicjovan** [comment]
@zablon-oigo please create a separate issue with step by step with how to reproduce

**Comment by aditya-armal** [comment]
There Should be a option for dark mode to use as per user's system setting. @miljkovicjovan

**Comment by miljkovicjovan** [comment]
@aditya-armal yes that would be a nice issue to add once we add the basic toggle switch
