### ISSUE TITLE
Complete all Active Tasks

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#58]
Add button with functionality to complete all active tasks

**Comment by IrfanSalim** [comment]
hey, I would like to work on this

**Comment by miljkovicjovan** [comment]
@IrfanSalim Okay I will assign this to you make sure you implement the features other buttons have. If you are stuck or have a question make sure to reach out.

**Comment by IrfanSalim** [comment]
Sure, thanks!

**Comment by IrfanSalim** [comment]
Hey, @miljkovicjovan 

I seem to be stuck somewhere, the button is working however its only completing one task at a time and also the confirmation modal is not showing on click.

I am raising a PR, can you check what I'm doing wrong, please?

**Comment by miljkovicjovan** [comment]
@IrfanSalim sure I will check it and let you know

**Comment by miljkovicjovan** [comment]
@IrfanSalim Thank you for contributing 😄 please continue to support the project by staring it or contributing with code or raising issues!
