### ISSUE TITLE
Remove tooltips on buttons on touch screen devices

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#6]

**Comment by Sky-De** [comment]
@miljkovicjovan what do you mean of tooltip?
Do you mean this?
![Screenshot 2023-10-31 032530](https://github.com/miljkovicjovan/minimalist-task-tracker/assets/79264045/be62da30-8d04-4b75-8575-f51aa1b66552)

if yes, so what exactly do you want? remove tooltip from mobile devices or make that to behave in another way
first clarify these 
then assign this to me 
thanks

**Comment by miljkovicjovan** [comment]
@Sky-De Yes that is what I meant by tooltip. 
I believe there is no need for any of the tooltips that we use to be available for touch screen devices since tooltips are good only for displaying info on hover. So I think a good solution is to just remove them complete on those devices.
I will rename the task to make it more clear and will assign to you.
