### ISSUE TITLE
Settings - Confirmations - Main switch needs to reflect children

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#62]
Issue 1:
- How to reproduce:
    1. Open settings modal on top right
    2. Turn any switch off
    
- Expected outcome: If one child switch is off the main should be off

- Status now:
<img width="400" alt="Screenshot 2023-11-05 at 18 18 00" src="https://github.com/miljkovicjovan/minimalist-task-tracker/assets/77690201/3e66aca9-652c-46f9-b85e-f087f9815157">

<hr/>

Issue 2:
- How to reproduce:
    1. Open settings modal on top right
    2. Turn main switch off
    3. Turn manually all children switches on

- Expected outcome: If all children switches are on the main switch should be on

- Status now:
<img width="400" alt="Screenshot 2023-11-05 at 18 24 14" src="https://github.com/miljkovicjovan/minimalist-task-tracker/assets/77690201/9f717553-1552-4b5b-9650-e7f79e7643d9">

**Comment by mallick03** [comment]
Hello, I would like to work on this issue.

**Comment by greatochuko** [comment]
HI, I would like to work on this issue
