### ISSUE TITLE
Time should be measured correctly wherever the user is

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#67]
CreatedAt variable should be correctly setUp and displayed no matter where the user is

**Comment by nitishpratap** [comment]
Hello @miljkovicjovan !
Can you please assign me to work on this issue.
Thank you!

**Comment by nitishpratap** [comment]
@miljkovicjovan Can you explain me this issue?

**Comment by miljkovicjovan** [comment]
I'm closing this issue since the Date() function gets the date and time from the system of the client and this issue is actually a non issue.
