### ISSUE TITLE
switch hover effects & states with bootstrap button outline

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#78]

**Comment by bhavik001** [comment]
Hello @miljkovicjovan !
Can you please assign me to work on this issue and can you please label this as a hactoberfest.

Please reply!
Thank you!

**Comment by bhavik001** [comment]
Hey @miljkovicjovan ,
Can you explain me this issue in detail?

**Comment by miljkovicjovan** [comment]
@bhavik001 we are using useState with a special class if the buttons are hovered to have an effect on them. However there is a built in class in bootstrap for button outline so we can use that.

**Comment by bhavik001** [comment]
Hi @miljkovicjovan 
Is this okay?
![hover](https://github.com/miljkovicjovan/minimalist-task-tracker/assets/95668553/339bff2c-b503-4dbb-a010-a4d554c64583)

This is the documentation: https://react-bootstrap.github.io/docs/components/buttons for outline

**Comment by miljkovicjovan** [comment]
@bhavik001 Yes that is correct we want this for all buttons and to delete the previous hover states which wont be needed

**Comment by bhavik001** [comment]
Hey @miljkovicjovan !
Can you please review and merge the code?

**Comment by bhavik001** [comment]
Hey @miljkovicjovan !
Can you look at the pull request I have created and if there is anything I have to change please let me know.

**Comment by bhavik001** [comment]
Hey @miljkovicjovan !
Can you look at the pull request I have created and if there is anything I have to change please let me know.

**Comment by bhavik001** [comment]
Hey @miljkovicjovan !
Can you look at the pull request I have created and if there is anything I have to change please let me know.
This is my pull request #85

**Comment by bhavik001** [comment]
Hey @miljkovicjovan !
Can you look at the pull request I have created and if there is anything I have to change please let me know. As I have to submit it to my professor and today is the last date to submit it.
This is my pull request #85
