### ISSUE TITLE
change description of website

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#79]
![IMG_1184](https://github.com/miljkovicjovan/minimalist-task-tracker/assets/77690201/5395db45-ca0b-41df-8b88-da437bf0fde6)

**Comment by divyakelaskar** [comment]
I would like to work on this. What should be the new description text?

**Comment by miljkovicjovan** [comment]
@divyakelaskar maybe "Minimalist task tracker using Local Storage" or if you have a better idea ?

**Comment by divyakelaskar** [comment]
> @divyakelaskar maybe "Minimalist task tracker using Local Storage"...

Sounds good.

**Comment by miljkovicjovan** [comment]
@all-contributors please add @divyakelaskar for code
