### ISSUE TITLE
Make logo loading faster

### ISSUE THREAD

**Issue by miljkovicjovan** [miljkovicjovan/minimalist-task-tracker#8]

**Comment by Sky-De** [comment]
@miljkovicjovan hi there, i would like to work on this, please assign it to me 
Thanks

**Comment by Sky-De** [comment]
@miljkovicjovan i took a look to other issues related to this project, i believe i can fix most or even all of them
You can assign all of them to me then I'll make sure there be no more issues within one week

**Comment by miljkovicjovan** [comment]
@Sky-De I will assign to you this issue and when you finish it you can choose another 😄 
Because I'm also working on multiple issues.
