### ISSUE TITLE
style : change settings dialog UI

### ISSUE THREAD

**Issue by divyakelaskar** [miljkovicjovan/minimalist-task-tracker#81]
### Description :
Simplify the UI by reducing text length.

### Context :
The current settings dialog UI has long, repetitive texts that give a less minimalistic vibe.

<img width="400" alt="image" src="https://github.com/miljkovicjovan/minimalist-task-tracker/assets/56636487/2180429d-2b6d-4151-8123-924df7843b53">

### Desired Output :
<img width="400" alt="image" src="https://github.com/miljkovicjovan/minimalist-task-tracker/assets/56636487/d1fe541f-e5d1-42f2-9c9c-dff81fb4022b">

**Comment by bhavik001** [comment]
Hello @miljkovicjovan  !
Can you please assign me to work on this issue and can you please label this as a hactoberfest.

Please reply!
Thank you!

**Comment by miljkovicjovan** [comment]
@all-contributors please add @bhavik001 for code
