### ISSUE TITLE
Bug: There is no way to go back from archived task, apart from browser back button

### ISSUE THREAD

**Issue by aditya-armal** [miljkovicjovan/minimalist-task-tracker#89]
After clicking on archived task there is button or way to go to homepage to create or view task, where there should have been one. I think I can take up the issue & raise PR once confirmed

**Comment by aditya-armal** [comment]
@miljkovicjovan Can you confirm this Issue, wanting to work on it.

**Comment by miljkovicjovan** [comment]
@aditya-armal hey you can work on it if you want and have a solution in mind but you can just use the logo, if you click it you go back. However if you have a better solution please do submit it
