### ISSUE TITLE
BUG: editing new task dosnt allow user to update, delete or confirm the editing of the task

### ISSUE THREAD

**Issue by aditya-armal** [miljkovicjovan/minimalist-task-tracker#90]
Button are disabled after the edit task option is chossen, even tried editing the task name, but still button are disable.I think I can take up the issue & raise PR once confirmed

**Comment by aditya-armal** [comment]
@miljkovicjovan Can you confirm this Issue, wanting to work on it.

**Comment by miljkovicjovan** [comment]
@aditya-armal Hello the buttons are disabled on purpose in order to finish the editing of the task. If you have an idea of implementing a confirm edit function of some sort please open a separate issue and you can take it up.
